const data: Catalog[] = [
  {
    folder: "1988.881232000",
    catalog: "1988-1",
    year: "1988",
    pages: [
      { fileName: "01", toyLine: "Front Cover" },
      { fileName: "02", toyLine: "The Real Ghostbusters" },
      { fileName: "03", toyLine: "The Real Ghostbusters" },
      { fileName: "04", toyLine: "The Real Ghostbusters" },
      { fileName: "05", toyLine: "The Real Ghostbusters" },
      { fileName: "06", toyLine: "The Real Ghostbusters" },
      { fileName: "07", toyLine: "The Real Ghostbusters" },
      { fileName: "08", toyLine: "Bone Age" },
      { fileName: "09", toyLine: "Bone Age" },
      { fileName: "10", toyLine: "Bone Age" },
      { fileName: "11", toyLine: "Bone Age" },
      { fileName: "12", toyLine: "Bone Age" },
      { fileName: "13", toyLine: "Bone Age" },
      { fileName: "14", toyLine: "Silverhawks" },
      { fileName: "15", toyLine: "Silverhawks" },
      { fileName: "16", toyLine: "Silverhawks" },
      { fileName: "17", toyLine: "Starting Lineup" },
      { fileName: "18", toyLine: "Starting Lineup" },
      { fileName: "19", toyLine: "Starting Lineup" },
      { fileName: "20", toyLine: "Starting Lineup" },
      { fileName: "21", toyLine: "Sky Commanders" },
      { fileName: "22", toyLine: "Sky Commanders" },
      { fileName: "23", toyLine: "Sky Commanders" },
      { fileName: "24", toyLine: "Sky Commanders" },
      { fileName: "25", toyLine: "M.A.S.K. Split Seconds" },
      { fileName: "26", toyLine: "M.A.S.K. Split Seconds" },
      { fileName: "27", toyLine: "M.A.S.K. Split Seconds" },
      { fileName: "28", toyLine: "M.A.S.K. Split Seconds" },
    ],
  },
];

export default data;
